### ISSUE TITLE
Proposed syntax

### ISSUE THREAD

**Issue by jamonserrano** [jamonserrano/postcss-plumber#1]
To remain closest to both regular CSS and the original SASS version and also to adhere to the [postcss plugin guidelines](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md) I propose the following syntax:

CSS input with a custom at-rule:

```css
p {
    @plumber {
        grid-height: 1rem;
        baseline: 0.158203;
        font-size: 1.75;
        line-height: 3;
        leading-top: 1;
        leading-bottom: 2;
    }
}
```

CSS output with the whole at-rule replaced:

```css
p {
    font-size: 1.75rem;
    line-height: 3rem;
    margin-top: 0;
    padding-top: 0.81641rem;
    padding-bottom: 0.18359rem;
    margin-bottom: 2rem;
}
```

Default parameters can be set in the plugin itself:

```js
// Gulpfile
var processors = [
    plumber({
        gridHeight: '1rem',
        baseline: 0.158203,
        fontSize: 1.75,
        lineHeight: 3,
        leadingTop: 1,
        leadingBottom: 2
    })
];
``` 

Your comments are welcome!
